### ISSUE TITLE
2 Fehler in 1415h 7c): Inverse-AMI-Code und Coderegelverletzung

### ISSUE THREAD

**Issue by felixdoerre** [weichweich/tele-loes#1]
Ich denke, da muss eine Coderegelverletzung am Anfang rein, und das sollte Inverser AMI code sein (also Ausschlag bei 0 und 0-Signal bei 1).

**Comment by weichweich** [comment]
Richtig Richtig... Sollte jetzt auch richtig sein. Danke!
